// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3X9xekxgsZjEG0NfZFJwVLO9M9p7n84',
    appId: '1:206864610582:android:0e0c6ec43cad7290660c37',
    messagingSenderId: '206864610582',
    projectId: 'flutter-snap-prod-5797d',
    storageBucket: 'flutter-snap-prod-5797d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStRncTGYpdjWjo0kT5F49yhwxXzz6aiU',
    appId: '1:206864610582:ios:d2ef4ec6c10d36b9660c37',
    messagingSenderId: '206864610582',
    projectId: 'flutter-snap-prod-5797d',
    storageBucket: 'flutter-snap-prod-5797d.firebasestorage.app',
    iosClientId:
        '206864610582-65porjhomolqggc4rs6nphnhe3ubba21.apps.googleusercontent.com',
    iosBundleId: 'com.snapAlanaam.fluttersnapalanaam',
  );
}
