// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQ3gMVswrhSF-4ESGTfr5b86yPuYQxAU',
    appId: '1:1017599447966:android:20ca3b7d6fffcab41d3c8f',
    messagingSenderId: '1017599447966',
    projectId: 'flutter-snap-env',
    storageBucket: 'flutter-snap-env.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXGiJBIOdofwX7hgBII_lX51BDvPn-Qo',
    appId: '1:1017599447966:ios:fa1bdb0636d9df421d3c8f',
    messagingSenderId: '1017599447966',
    projectId: 'flutter-snap-env',
    storageBucket: 'flutter-snap-env.firebasestorage.app',
    iosClientId:
        '1017599447966-rp8cm612e9pht3d994o7gj8f9n6165er.apps.googleusercontent.com',
    iosBundleId: 'com.snapAlanaam.fluttersnapalanaam.dev',
  );
}
